import './css/normalize.css'
import './css/variables.css'
import './css/styles.css'
import './css/header.css'
import './css/hero.css'
import './css/caracteristicas.css'
import './css/planes.css'
import './css/footer.css'